version: "3.9"

services:
  app:
    build:
      context: .
    depends_on:
      - db
      - redis
      - queue
    ports:
      - ${HOST_APP_PORT:-80}:8080
    volumes:
      - .:/app

  db:
    image: postgres:14.4
    ports:
      - ${HOST_POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}

  redis:
    command: redis-server --requirepass ${REDIS_PASSWORD:-app}
    image: redis:5.0.7
    ports:
      - ${HOST_REDIS_PORT:-6379}:6379

  queue:
    image: rabbitmq:3.8.3-management
    ports:
      - ${DOCKER_HOST_QUEUE_PORT:-15672}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${MESSEGNER_TRANSPORT_USER:-"queue"}
      RABBITMQ_DEFAULT_PASS: ${MESSEGNER_TRANSPORT_PASSWORD:-"queue"}
